### ISSUE TITLE
package name should not be capitalized

### ISSUE THREAD

**Issue by anthonykulis** [anthonykulis/automobile#38]
see `Truck`

https://github.com/anthonykulis/automobile/tree/master/edu/jalc/automobile/onlinebuilder/components/body/Truck

1 point

**Comment by nourelhoda89** [comment]
will work on this as well

**Comment by anthonykulis** [comment]
Last one until you the PR done. Once you do, start picking out more

**Comment by anthonykulis** [comment]
sorry nour. i got this on accident. I will give you credit, but your out of date repo caused a merge conflict
