### ISSUE TITLE
needs descriptive meaningful `toString`

### ISSUE THREAD

**Issue by anthonykulis** [anthonykulis/automobile#48]
requirement was to cascade `toString` on all components and parts

https://github.com/anthonykulis/automobile/blob/master/edu/jalc/automobile/onlinebuilder/components/body/Body.java#L40

2 points

**Comment by nourelhoda89** [comment]
and this

**Comment by anthonykulis** [comment]
All yours

**Comment by anthonykulis** [comment]
if you are claiming, please complete in a timely manner. dont have to rush it, but if you dont complete it soon, I will let others take it. :)

**Comment by anthonykulis** [comment]
actually, I reviewed the code. `SUV` and `Truck` both have `toString`. Do this for `Car` instead please.
