### ISSUE TITLE
CoupeBody is not public

### ISSUE THREAD

**Issue by KenanJones** [anthonykulis/automobile#85]
@anthonykulis 
CoupeBody is not public, so I couldn't use it. 
I have changed it to public on my repo, but the other car team will need it too.
looks like all the other classes extending body are public.

**Comment by anthonykulis** [comment]
Stop changing things on your public repo. seriously. If there is an issue
on the core source, fork the repo into a new one, fix the issue, and make a
pr. if you change the core in your repo, 10 other people will not have the
source. if everyone did that, everything is broken. tag me when you create
the new pr. i will give +1 ec on this.

**Comment by KenanJones** [comment]
@anthonykulis 
I also fixed some smaller errors I found. I have made the pr.

**Comment by anthonykulis** [comment]
thanks

**Comment by anthonykulis** [comment]
done.
